# Generated by Django 5.0.3 on 2025-04-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_pics_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
